### ISSUE TITLE
Request for code related to word embedding

### ISSUE THREAD

**Issue by zhoubay** [lucmos/relreps#20]
Hi Luca,

I'm curious about your work about comparing communicating different word embeddings latent space, but I find it hard to figure out which part of your repo is about this.

Could you be so kind to point them out for me?

Thank you!
Xibin

**Comment by lucmos** [comment]
Most of the figures and tables in the paper have an associated notebook in the [`experiments`](https://github.com/lucmos/relreps/tree/main/experiments) folder. I think you can start looking into that, starting from the experiment that interests you.

The python package (under `src`) provides utilities as a library, I would dive into it if it is required by the notebook you are looking at. 

Please let me know if you have any other questions!

**Comment by zhoubay** [comment]
Thank you for your reply! I'll check it.
